---
kind: pipeline
type: docker
name: default

steps:
- name: compile
  image: docker.io/procsiab/texlive-it:latest-amd64
  commands:
  - make all

- name: deploy
  image: appleboy/drone-scp
  settings:
    host: 192.168.1.100
    username: astro
    key:
      from_secret: astro-drone-key
    port: 22
    target: /srv/book/
    source: pdf/psi-2019.pdf
    strip_components: 1
  when:
    branch:
    - master
    status:
    - success

- name: debug
  image: docker.io/busybox:latest
  commands:
  - cat pdf/main.log
  when:
    branch:
    - master
    status:
    - failure

---
kind: signature
hmac: eab85fdff5c694978eff2b6adc0ad15a575873bedc135aa8d00155160e0fa07c

...
