---
kind: pipeline
name: default

platform:
  os: linux
  arch: arm

steps:
- name: compile
  image: texlive-rpi-it
  commands:
  - make all

- name: deploy
  image: none
  volumes:
  - name: files
    path: ~/files
  commands:
  - export FILENAME="Probabilità e Statistica per l' Informatica.pdf"
  - cp pdf/psi-2019.pdf ~/files/$FILENAME
  when:
    status:
    - success

volumes:
- name: files
  host:
    path: /srv/fs-data
---
kind: signature
hmac: e27d3e41e7bfb3c5fbea981fd68f3db71315bd62f6d76698f09017b35ebdaee9

...
